export const GET_LANGUAGE = "GET_LANGUAGE";
export const SET_LANGUAGE = "SET_LANGUAGE";

export const SET_SITE_ID = "SET_SITE_ID";
export const SET_ITEM_ID_KNOWN = "SET_ITEM_ID_KNOWN";
export const SET_SELLER = "SET_SELLER";
export const SET_SELLER_ITEMS = "SET_SELLER_ITEMS";
export const SET_ITEM_ID = "SET_ITEM_ID";
export const SET_ITEM = "SET_ITEM";

export const LOAD_APPLICATION_SETTINGS = "LOAD_APPLICATION_SETTINGS";
